package io.github.voodoo262.jdbc.moca;

import io.github.voodoo262.jdbc.moca.protocol.MocaClient;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLNonTransientConnectionException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * A JDBC {@link Connection} backed by one MOCA session.
 *
 * <p>Transactions are server-side: {@code autocommit} is an attribute on every request,
 * and {@code commit}/{@code rollback} are ordinary MOCA commands. There is nothing to
 * commit until a command has actually run, so the connection tracks whether one has.
 */
final class MocaConnection implements Connection
{
    private final MocaClient client;
    /** Already redacted by {@code MocaUrl}: this is handed out by {@code getMetaData().getURL()}. */
    private final String url;
    private final String user;

    /**
     * Statements handed out by this connection, so {@link #close()} can honour the JDBC
     * rule that closing a connection releases them. Identity-based: two statements are
     * never "equal", and a Statement has no business being hashed by value.
     */
    private final java.util.Set<MocaStatement> statements =
            java.util.Collections.newSetFromMap(new java.util.IdentityHashMap<>());

    private boolean autoCommit = true;
    private boolean readOnly;
    /** True once a command has run under {@code autoCommit == false}. */
    private boolean inTransaction;
    private boolean closed;

    MocaConnection(final MocaClient client, final String url, final String user)
    {
        this.client = client;
        this.url = url;
        this.user = user;
    }

    MocaClient getClient()
    {
        return client;
    }

    /** Called by {@link MocaStatement} after each command, to know whether a commit is owed. */
    void noteExecuted()
    {
        if (!autoCommit)
        {
            inTransaction = true;
        }
    }

    String getUrl() { return url; }

    String getUser() { return user; }

    // ------------------------------------------------------------- statements

    @Override
    public Statement createStatement() throws SQLException
    {
        requireOpen();
        return register(new MocaStatement(this));
    }

    @Override
    public PreparedStatement prepareStatement(final String sql) throws SQLException
    {
        requireOpen();
        return register(new MocaPreparedStatement(this, sql));
    }

    private <T extends MocaStatement> T register(final T statement)
    {
        statements.add(statement);
        return statement;
    }

    /** Called by {@link MocaStatement#close()} so a long-lived connection does not accumulate them. */
    void forget(final MocaStatement statement)
    {
        statements.remove(statement);
    }

    // The result-set type/concurrency arguments are accepted rather than rejected:
    // every MOCA result is already scroll-insensitive and read-only, which satisfies
    // any request for something weaker. A request for an *updatable* cursor cannot be
    // satisfied and is refused.
    @Override
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency) throws SQLException
    {
        requireReadOnlyConcurrency(resultSetConcurrency);
        return createStatement();
    }

    @Override
    public Statement createStatement(final int t, final int c, final int h) throws SQLException
    {
        requireReadOnlyConcurrency(c);
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int t, final int c) throws SQLException
    {
        requireReadOnlyConcurrency(c);
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int t, final int c, final int h)
            throws SQLException
    {
        requireReadOnlyConcurrency(c);
        return prepareStatement(sql);
    }

    private void requireReadOnlyConcurrency(final int concurrency) throws SQLException
    {
        if (concurrency != java.sql.ResultSet.CONCUR_READ_ONLY)
        {
            throw unsupported("Updatable result sets");
        }
    }

    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException { throw unsupported("Generated keys"); }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException { throw unsupported("Generated keys"); }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException { throw unsupported("Generated keys"); }

    @Override public CallableStatement prepareCall(String sql) throws SQLException { throw unsupported("Callable statements"); }
    @Override public CallableStatement prepareCall(String sql, int t, int c) throws SQLException { throw unsupported("Callable statements"); }
    @Override public CallableStatement prepareCall(String sql, int t, int c, int h) throws SQLException { throw unsupported("Callable statements"); }

    @Override
    public String nativeSQL(final String sql) throws SQLException
    {
        requireOpen();
        // MOCA has no JDBC escape syntax to translate, so the only transformation is the
        // one the driver really does apply: bracketing a bare SELECT so MOCA passes it
        // through to the database underneath.
        return MocaStatement.bracketBareSelect(sql);
    }

    // ----------------------------------------------------------- transactions

    @Override
    public void setAutoCommit(final boolean autoCommit) throws SQLException
    {
        requireOpen();
        if (this.autoCommit == autoCommit) return;
        // Switching on autocommit while work is outstanding must not silently drop it.
        if (autoCommit && inTransaction)
        {
            commit();
        }
        this.autoCommit = autoCommit;
    }

    @Override
    public boolean getAutoCommit() throws SQLException
    {
        requireOpen();
        return autoCommit;
    }

    @Override
    public void commit() throws SQLException
    {
        requireOpen();
        if (autoCommit)
        {
            throw new SQLException("commit() is not allowed while auto-commit is on", "25000");
        }
        if (!inTransaction) return; // nothing has run; committing would be a wasted round trip
        client.execute("commit", true);
        inTransaction = false;
    }

    @Override
    public void rollback() throws SQLException
    {
        requireOpen();
        if (autoCommit)
        {
            throw new SQLException("rollback() is not allowed while auto-commit is on", "25000");
        }
        if (!inTransaction) return;
        client.execute("rollback", true);
        inTransaction = false;
    }

    @Override
    public int getTransactionIsolation() throws SQLException
    {
        requireOpen();
        // MOCA exposes no isolation control; whatever the underlying database does is
        // what you get, and the driver cannot report it.
        return TRANSACTION_NONE;
    }

    @Override
    public void setTransactionIsolation(final int level) throws SQLException
    {
        requireOpen();
        if (level != TRANSACTION_NONE)
        {
            throw unsupported("Setting transaction isolation");
        }
    }

    @Override public Savepoint setSavepoint() throws SQLException { throw unsupported("Savepoints"); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { throw unsupported("Savepoints"); }
    @Override public void rollback(Savepoint savepoint) throws SQLException { throw unsupported("Savepoints"); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw unsupported("Savepoints"); }

    // ---------------------------------------------------------------- lifecycle

    @Override
    public void close() throws SQLException
    {
        if (closed) return;
        try
        {
            // JDBC leaves the fate of an open transaction to the driver. Rolling back
            // is the safe reading: work the caller never committed should not land
            // because they closed the connection.
            if (!autoCommit && inTransaction)
            {
                rollback();
            }
        }
        finally
        {
            // JDBC: closing a connection closes the statements it created, and their
            // result sets. Copy first — Statement.close() calls back into forget().
            for (final MocaStatement statement : new java.util.ArrayList<>(statements))
            {
                statement.close();
            }
            statements.clear();
            inTransaction = false;
            closed = true;
            client.close();
        }
    }

    @Override
    public boolean isClosed()
    {
        return closed || client.isClosed();
    }

    @Override
    public boolean isValid(final int timeout) throws SQLException
    {
        if (timeout < 0)
        {
            throw new SQLException("timeout must not be negative", "HY000");
        }
        if (isClosed()) return false;
        // 0 means "no limit", per the JDBC contract.
        return client.ping(timeout == 0 ? null : java.time.Duration.ofSeconds(timeout));
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException
    {
        requireOpen();
        return new MocaDatabaseMetaData(this);
    }

    // -------------------------------------------------------------------- misc

    @Override
    public void setReadOnly(final boolean readOnly) throws SQLException
    {
        requireOpen();
        // Recorded as a hint. The driver cannot enforce it: MOCA commands are opaque
        // strings, so there is no way to tell a reading command from a writing one.
        this.readOnly = readOnly;
    }

    @Override public boolean isReadOnly() throws SQLException { requireOpen(); return readOnly; }

    // MOCA has no catalogs or schemas of its own.
    @Override public void setCatalog(String catalog) throws SQLException { requireOpen(); }
    @Override public String getCatalog() throws SQLException { requireOpen(); return null; }
    @Override public void setSchema(String schema) throws SQLException { requireOpen(); }
    @Override public String getSchema() throws SQLException { requireOpen(); return null; }

    @Override public void setHoldability(int holdability) throws SQLException { requireOpen(); }
    @Override public int getHoldability() throws SQLException { requireOpen(); return java.sql.ResultSet.HOLD_CURSORS_OVER_COMMIT; }

    @Override public SQLWarning getWarnings() throws SQLException { requireOpen(); return null; }
    @Override public void clearWarnings() throws SQLException { requireOpen(); }

    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { throw unsupported("Type maps"); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { throw unsupported("Type maps"); }

    @Override public Clob createClob() throws SQLException { throw unsupported("CLOB values"); }
    @Override public Blob createBlob() throws SQLException { throw unsupported("BLOB values"); }
    @Override public NClob createNClob() throws SQLException { throw unsupported("NCLOB values"); }
    @Override public SQLXML createSQLXML() throws SQLException { throw unsupported("SQLXML values"); }
    @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { throw unsupported("ARRAY values"); }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { throw unsupported("STRUCT values"); }

    @Override
    public void setClientInfo(final String name, final String value) throws SQLClientInfoException
    {
        throw new SQLClientInfoException("Client info is not supported by the MOCA JDBC driver", null);
    }

    @Override
    public void setClientInfo(final Properties properties) throws SQLClientInfoException
    {
        throw new SQLClientInfoException("Client info is not supported by the MOCA JDBC driver", null);
    }

    @Override public String getClientInfo(String name) { return null; }
    @Override public Properties getClientInfo() { return new Properties(); }

    @Override
    public void abort(final Executor executor) throws SQLException
    {
        // No cancel channel exists, so the strongest thing abort can do is close.
        close();
    }

    @Override
    public void setNetworkTimeout(final Executor executor, final int milliseconds) throws SQLException
    {
        // The timeout is fixed when the connection is opened (the readTimeout property);
        // the JDK's HttpClient will not let it change afterwards.
        throw unsupported("Changing the network timeout after connecting");
    }

    @Override
    public int getNetworkTimeout() throws SQLException
    {
        throw unsupported("Reading the network timeout");
    }

    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException
    {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException(getClass().getName() + " is not a wrapper for " + iface.getName(), "HY000");
    }

    @Override
    public boolean isWrapperFor(final Class<?> iface)
    {
        return iface.isInstance(this);
    }

    private void requireOpen() throws SQLException
    {
        if (isClosed())
        {
            throw new SQLNonTransientConnectionException("Connection is closed", "08003");
        }
    }

    private static SQLFeatureNotSupportedException unsupported(final String what)
    {
        return new SQLFeatureNotSupportedException(what + " is not supported by the MOCA JDBC driver");
    }
}
